replicaCount: 1

podAnnotations:
  linkerd.io/inject: enabled

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-staging

jaeger:
  collector_host: dns:///jaeger-staging-collector-headless.observability:14250

image:
  repository: registry.happytravel.com/sunpu
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
  hosts:
    - host: sunpu-staging.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: happytravel-tls
     hosts:
       - sunpu-staging.happytravel.com

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: false
  podMonitor:
    enabled: false

env:
  ASPNETCORE_URLS: http://*:80
  ASPNETCORE_ENVIRONMENT: "Staging"
  HTDC_VAULT_ENDPOINT: "http://vault.staging.svc.k8s.dev:8200/v1/"
  HTDC_SUNPU_SENTRY_ENDPOINT: "https://5b342f0cc9dc41f7be37281d22b662ed@sentry.happytravel.com/60"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  CONSUL_HTTP_ADDR: "http://consul-consul-server.staging.svc.k8s.dev:8500/"
  HTDC_REDIS_HOST: "redis-sunpu"